"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PermissionTree = exports.Permission = void 0;
var Permission = /** @class */ (function () {
    function Permission(name, value, groupName, description) {
        this.name = name;
        this.value = value;
        this.groupName = groupName;
        this.description = description;
    }
    Permission.viewUsersPermission = "systemsetting.user.view";
    Permission.manageUsersPermission = "systemsetting.user.manage";
    Permission.viewRolesPermission = "systemsetting.role.view";
    Permission.manageRolesPermission = "systemsetting.role.manage";
    Permission.assignRolesPermission = "systemsetting.role.assign";
    Permission.viewFacilitiesPermission = "frsmgt.equipment.view";
    Permission.manageFacilitiesPermission = "frsmgt.equipment.manage";
    Permission.viewFacilityTypesPermission = "frsmgt.equipmenttype.view";
    Permission.manageFacilityTypesPermission = "frsmgt.equipmenttype.manage";
    Permission.viewSmartRoomSchedulerLogsPermission = "frsmgt.smartroomschedulerlog.view";
    Permission.addReservationsPermission = "frsmgt.calendar.view";
    Permission.manageReservationsPermission = "frsmgt.calendar.view";
    Permission.viewDevicesPermission = "sgnmanagement.devicemgt.device.view";
    Permission.manageDevicesPermission = "sgnmanagement.devicemgt.device.manage";
    Permission.approveDevicesPermission = "sgnmanagement.devicemgt.device.approve";
    Permission.viewLocationsPermission = "systemsetting.locationtree.view";
    Permission.manageLocationsPermission = "systemsetting.locationtree.manage";
    Permission.viewInstitutionsPermission = "systemsetting.institution.view";
    Permission.manageInstitutionsPermission = "systemsetting.institution.manage";
    Permission.viewDepartmentsPermission = "systemsetting.department.view";
    Permission.manageDepartmentsPermission = "systemsetting.department.manage";
    Permission.viewContactGroupsPermission = "frsmgt.accesscontrol.contactgroup.view";
    Permission.manageContactGroupsPermission = "frsmgt.accesscontrol.contactgroup.manage";
    Permission.viewUserPhonebooksPermission = "frsmgt.accesscontrol.phonebook.view";
    Permission.manageUserPhonebooksPermission = "frsmgt.accesscontrol.phonebook.manage";
    Permission.viewReportsPermission = "reportmgt.facilitymgt.view";
    Permission.viewVehicleLogsPermission = "reportmgt.facilitymgt.vehiclelog.view";
    Permission.viewOccupancyLogsPermission = "reportmgt.facilitymgt.occupancylog.view";
    Permission.viewPIBTemplatesPermission = "pibtemplates.view";
    Permission.managePIBTemplatesPermission = "pibtemplates.manage";
    Permission.viewPIBDevicesTemplatesPermission = "pibdevices.view";
    Permission.managePIBDevicesTemplatesPermission = "pibdevices.manage";
    Permission.viewEpaperTemplatesPermission = "sgnmanagement.epapermgt.view";
    Permission.manageEpaperTemplatesPermission = "sgnmanagement.epapermgt.manage";
    Permission.viewEpaperDevicesPermission = "epaperdevices.view";
    Permission.manageEpaperDevicesPermission = "epaperdevices.manage";
    Permission.viewDashboardPermission = "systemsetting.dashboard.view";
    Permission.manageUserVehiclesPermission = "frsmgt.accesscontrol.uservehicle.manage";
    //public static readonly viewCalendarPermission: PermissionValues = "calendar.view";
    Permission.approvePublicationsPermission = "frsmgt.accesscontrol.publication.approve";
    Permission.emailPublicationsPermission = "frsmgt.accesscontrol.publication.email";
    Permission.createComponentsPermission = "sgnmanagement.contentmanagement.component.create";
    Permission.updateComponentsPermission = "sgnmanagement.contentmanagement.component.update";
    Permission.deleteComponentsPermission = "sgnmanagement.contentmanagement.component.delete";
    Permission.createCompilationsPermission = "sgnmanagement.contentmanagement.compilation.create";
    Permission.updateCompilationsPermission = "sgnmanagement.contentmanagement.compilation.update";
    Permission.deleteCompilationsPermission = "sgnmanagement.contentmanagement.compilation.delete";
    Permission.createPublicationsPermission = "sgnmanagement.contentmanagement.publication.create";
    Permission.updatePublicationsPermission = "sgnmanagement.contentmanagement.publication.update";
    Permission.deletePublicationsPermission = "sgnmanagement.contentmanagement.publication.delete";
    Permission.viewSignageDashboardPermission = "systemsetting.dashboard.sgn.view";
    Permission.pushmessageSignageControlPermission = "systemsetting.dashboard.sgn.controls.pushmessage";
    Permission.previewSignageControlPermission = "systemsetting.dashboard.sgn.controls.preview";
    Permission.rebootSignageControlPermission = "systemsetting.dashboard.sgn.controls.reboot";
    Permission.refreshSignageControlPermission = "systemsetting.dashboard.sgn.controls.refresh";
    Permission.screenshotSignageControlPermission = "systemsetting.dashboard.sgn.controls.screenshot";
    Permission.deviceinfoSignageControlPermission = "systemsetting.dashboard.sgn.controls.deviceinfo";
    Permission.publicationSignageControlPermission = "systemsetting.dashboard.sgn.controls.publication";
    Permission.viewUserGroupsPermission = "systemsetting.usergroup.view";
    Permission.manageUserGroupsPermission = "systemsetting.usergroup.manage";
    Permission.viewAuthLogsPermission = "systemsetting.audit.authlog.view";
    Permission.viewUpDownTimeLogsPermission = "reportmgt.sgn.updownlog.view";
    Permission.viewDataLogsPermission = "systemsetting.audit.datalog.view";
    Permission.viewImageReferenceTypesPermission = "systemsetting.imagereferencetype.view";
    Permission.manageImageReferenceTypesPermission = "systemsetting.imagereferencetype.manage";
    Permission.viewImageReferenceColorsPermission = "systemsetting.imagereferencecolor.view";
    Permission.manageImageReferenceColorsPermission = "systemsetting.imagereferencecolor.manage";
    Permission.viewDeviceTypesPermission = "systemsetting.devicetype.view";
    Permission.manageDeviceTypesPermission = "systemsetting.devicetype.manage";
    Permission.viewAssetTypesPermission = "assetmgt.assettype.view";
    Permission.manageAssetTypesPermission = "assetmgt.assettype.manage";
    Permission.viewAssetModelsPermission = "assetmgt.assetmodel.view";
    Permission.manageAssetModelsPermission = "assetmgt.assetmodel.manage";
    Permission.viewAssetsPermission = "assetmgt.asset.view";
    Permission.manageAssetsPermission = "assetmgt.asset.manage";
    Permission.viewServiceContractsPermission = "assetmgt.servicecontract.view";
    Permission.manageServiceContractsPermission = "assetmgt.servicecontract.manage";
    Permission.viewEmailQueuesPermission = "systemsetting.emailqueue.view";
    return Permission;
}());
exports.Permission = Permission;
var PermissionTree = /** @class */ (function () {
    function PermissionTree(id, value, type, children) {
        this.id = id;
        this.value = value;
        this.children = children;
    }
    return PermissionTree;
}());
exports.PermissionTree = PermissionTree;
//# sourceMappingURL=permission.model.js.map