<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTO\PaymentModels\ErrorViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="2.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FRS\DAL\DAL.csproj" />
  </ItemGroup>

</Project>
